package pages;

public enum PageType {
    LOGIN_PAGE,
    INFORMATION_PANEL_PAGE,
    ADMIN_TOOLS_PAGE,
    USER_AND_GROUPS_PAGE,
    SETTINGS_PAGE,
    HR_PAGE,
    PRODUCT_PAGE,
    COMPANY_PAGE, MODULES_PAGE, CREATE_GROUP_PAGE, THIRD_PARTIES_PAGE
}
